version: 1
api_server:
  workers: 6
  grpc:
    reflection:
      enabled: true
runners:
  logging:
    access:
      enabled: false
  dit-predictor:
    resources: system
  en-reader:
    resources: system
